### ISSUE TITLE
invalid memory address

### ISSUE THREAD

**Issue by djroach** [bemasher/rtlamr-collect#25]
Getting invalid memory address or nil pointer dereference. Setup environment variables, database etc. Same error whether IDM or SCM. 

```
pi@raspberrypi:~/go/src/github.com/bemasher/rtlamr-collect $ sudo systemctl status rtlamr-collect
● rtlamr-collect.service - RTLAMR Collector
   Loaded: loaded (/etc/systemd/system/rtlamr-collect.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2019-11-23 01:46:57 GMT; 4min 31s ago
 Main PID: 1185 (sh)
    Tasks: 13 (limit: 4915)
   CGroup: /system.slice/rtlamr-collect.service
           ├─1185 /bin/sh -c /home/pi/go/bin/rtlamr | /home/pi/go/bin/rtlamr-collect
           └─1186 /home/pi/go/bin/rtlamr

Nov 23 01:46:57 raspberrypi sh[1185]: 01:46:57.601003 main.go:119: GainCount: 29
Nov 23 01:46:57 raspberrypi sh[1185]: 01:46:57.644966 main.go:388: preloaded 0 meters
Nov 23 01:51:19 raspberrypi sh[1185]: 01:51:19.655281 main.go:457: rtlamr,endpoint_id=20876520,endpoint_type=7,msg_type=cumulative,protocol=SCM co
Nov 23 01:51:19 raspberrypi sh[1185]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 23 01:51:19 raspberrypi sh[1185]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x24 pc=0x149e4]
Nov 23 01:51:19 raspberrypi sh[1185]: goroutine 1 [running]:
Nov 23 01:51:19 raspberrypi sh[1185]: panic(0x2472f0, 0x1060c010)
Nov 23 01:51:19 raspberrypi sh[1185]:         /usr/lib/go-1.7/src/runtime/panic.go:500 +0x33c
Nov 23 01:51:19 raspberrypi sh[1185]: main.main()
Nov 23 01:51:19 raspberrypi sh[1185]:         /home/pi/go/src/github.com/bemasher/rtlamr-collect/main.go:461 +0xb88
lines 1-19/19 (END)
```

**Comment by bemasher** [comment]
I would also recommend that you upgrade your go toolchain and re-build both rtlamr-collect and rtlamr. Around about go 1.10 or so, there were some significant improvements to compiler optimizations and performance on ARM systems.

**Comment by djroach** [comment]
This did fix it.Thank you
